package com.example.walletwizard.Model

import com.example.walletwizard.R

data class ChooseIconData(
    val icon:Int
)


fun iconList():List<ChooseIconData>{
    return listOf(

        ChooseIconData(R.drawable.home),
        ChooseIconData(R.drawable.beach),
        ChooseIconData(R.drawable.bill),
        ChooseIconData(R.drawable.cart),
        ChooseIconData(R.drawable.shopping_bag),
        ChooseIconData(R.drawable.car),
        ChooseIconData(R.drawable.income),
        ChooseIconData(R.drawable.gift),
        ChooseIconData(R.drawable.heart),
        ChooseIconData(R.drawable.headphone),
        ChooseIconData(R.drawable.gym),
        ChooseIconData(R.drawable.plane),
        ChooseIconData(R.drawable.rocket),
        ChooseIconData(R.drawable.clothes),
        ChooseIconData(R.drawable.shoes),
        ChooseIconData(R.drawable.dinner),
        ChooseIconData(R.drawable.cocktail),
        ChooseIconData(R.drawable.doctor),
        ChooseIconData(R.drawable.dog_footprint),
        ChooseIconData(R.drawable.football),
        ChooseIconData(R.drawable.home),
        ChooseIconData(R.drawable.beach),
        ChooseIconData(R.drawable.bill),
        ChooseIconData(R.drawable.cart),
        ChooseIconData(R.drawable.shopping_bag),
        ChooseIconData(R.drawable.car),
        ChooseIconData(R.drawable.income),
        ChooseIconData(R.drawable.gift),
        ChooseIconData(R.drawable.heart),
        ChooseIconData(R.drawable.headphone),
        ChooseIconData(R.drawable.gym),
        ChooseIconData(R.drawable.plane),
        ChooseIconData(R.drawable.rocket),
        ChooseIconData(R.drawable.clothes),
        ChooseIconData(R.drawable.shoes),
        ChooseIconData(R.drawable.dinner),
        ChooseIconData(R.drawable.cocktail),
        ChooseIconData(R.drawable.doctor),
        ChooseIconData(R.drawable.dog_footprint),
        ChooseIconData(R.drawable.football),
        ChooseIconData(R.drawable.home),
        ChooseIconData(R.drawable.beach),
        ChooseIconData(R.drawable.bill),
        ChooseIconData(R.drawable.cart),
        ChooseIconData(R.drawable.shopping_bag),
        ChooseIconData(R.drawable.car),
        ChooseIconData(R.drawable.income),
        ChooseIconData(R.drawable.gift),
        ChooseIconData(R.drawable.heart),
        ChooseIconData(R.drawable.headphone),
        ChooseIconData(R.drawable.gym),
        ChooseIconData(R.drawable.plane),
        ChooseIconData(R.drawable.rocket),
        ChooseIconData(R.drawable.clothes),
        ChooseIconData(R.drawable.shoes),
        ChooseIconData(R.drawable.dinner),
        ChooseIconData(R.drawable.cocktail),
        ChooseIconData(R.drawable.doctor),
        ChooseIconData(R.drawable.dog_footprint),
        ChooseIconData(R.drawable.football),
        ChooseIconData(R.drawable.home),
        ChooseIconData(R.drawable.beach),
        ChooseIconData(R.drawable.bill),
        ChooseIconData(R.drawable.cart),
        ChooseIconData(R.drawable.shopping_bag),
        ChooseIconData(R.drawable.car),
        ChooseIconData(R.drawable.income),
        ChooseIconData(R.drawable.gift),
        ChooseIconData(R.drawable.heart),
        ChooseIconData(R.drawable.headphone),
        ChooseIconData(R.drawable.gym),
        ChooseIconData(R.drawable.plane),
        ChooseIconData(R.drawable.rocket),
        ChooseIconData(R.drawable.clothes),
        ChooseIconData(R.drawable.shoes),
        ChooseIconData(R.drawable.dinner),
        ChooseIconData(R.drawable.cocktail),
        ChooseIconData(R.drawable.doctor),
        ChooseIconData(R.drawable.dog_footprint),
        ChooseIconData(R.drawable.football),

    )
}